import { useCallback, useEffect, useState } from 'react'
import { WORKER, workerPost } from '../lib/points'
import { derive, sha256hex, GAME_OPTS } from '../lib/fair'
import styles from './ProvablyFair.module.css'

const GAME_NAMES = { mines: 'Mines', blackjack: 'Blackjack', keno: 'Keno', plinko: 'Plinko', roulette: 'Roulette', crash: 'Crash', jackpot: 'Jackpot' }
const when = (iso) => { const d = new Date(iso); return Number.isNaN(d.getTime()) ? '-' : d.toLocaleString('pt-PT', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' }) }
const short = (s) => (s ? `${s.slice(0, 8)}…${s.slice(-6)}` : '-')

function Copy({ text }) {
  const [ok, setOk] = useState(false)
  return <button type="button" className={styles.copy} onClick={() => { navigator.clipboard?.writeText(text).then(() => { setOk(true); setTimeout(() => setOk(false), 1200) }).catch(() => {}) }}>{ok ? 'Copied' : 'Copy'}</button>
}
const Field = ({ label, value, copy = true }) => (
  <div className={styles.fld}>
    <span className={styles.lab}>{label}</span>
    <div className={styles.box}><code>{value || '-'}</code>{copy && value ? <Copy text={value} /> : null}</div>
  </div>
)

function Overview() {
  return (
    <div className={styles.pane}>
      <p>Every bet outcome is determined by a cryptographic combination of three values:</p>
      <pre className={styles.code}>HMAC-SHA256(serverSeed, clientSeed:nonce:block)</pre>
      <ul>
        <li><b>Server Seed</b> - generated by us before the round. We commit to its SHA-256 hash, so it cannot be changed after you bet.</li>
        <li><b>Client Seed</b> - set by you. Change it any time from the Seeds tab.</li>
        <li><b>Nonce</b> - a counter that rises with every bet, so the same seed pair gives a new result each time.</li>
      </ul>
      <p>After you rotate your seeds, the old server seed is revealed. Use the Verify tab to recompute any result yourself. Every round you play is logged with its hash, client seed and nonce.</p>
      <pre className={styles.code}>sha256(serverSeed) === serverSeedHash</pre>
    </div>
  )
}

function Seeds({ onVerify }) {
  const [st, setSt] = useState(null), [rounds, setRounds] = useState([]), [cs, setCs] = useState(''), [busy, setBusy] = useState(false), [err, setErr] = useState('')
  const load = useCallback(async () => {
    const [a, b] = await Promise.all([workerPost('/fair/state'), workerPost('/fair/rounds')])
    if (!a.ok) { setErr(a.data?.error === 'not_logged_in' ? 'Log in to see your seeds.' : 'Could not load your seeds.'); return }
    setErr(''); setSt(a.data); setCs((v) => v || a.data.client || ''); setRounds(b.ok ? b.data.rounds || [] : [])
  }, [])
  useEffect(() => { load() }, [load])
  const rotate = async () => {
    setBusy(true)
    const r = await workerPost('/fair/rotate', { clientSeed: cs })
    setBusy(false)
    if (r.ok) { setSt(r.data); setCs(''); load() } else setErr('Could not rotate. Try again.')
  }
  if (err) return <div className={styles.pane}><p>{err}</p></div>
  if (!st) return <div className={styles.pane}><p>Loading...</p></div>
  return (
    <div className={styles.pane}>
      <Field label="Server seed hash" value={st.hash} />
      <Field label="Previous server seed (revealed)" value={st.prev?.serverSeed} />
      <Field label="Client seed" value={st.client} />
      <div className={styles.fld}><span className={styles.lab}>Nonce (bets placed with current pair)</span><b className={styles.nonce}>{st.nonce}</b></div>
      <label className={styles.fld}><span className={styles.lab}>New client seed</span><input className={styles.in} value={cs} maxLength={64} onChange={(e) => setCs(e.target.value)} placeholder="Leave empty for a random one" /></label>
      <button type="button" className={styles.cta} onClick={rotate} disabled={busy}>Rotate Seeds</button>
      <p className={styles.note}>Rotating reveals the current server seed and starts a fresh pair.</p>
      <h4 className={styles.h4}>Your recent bets</h4>
      {!rounds.length ? <p className={styles.note}>No bets yet.</p> : (
        <div className={styles.tbl}>
          {rounds.map((r, i) => (
            <div key={i} className={styles.tr}>
              <span>{GAME_NAMES[r.game] || r.game}</span><span>nonce {r.nonce}{r.ball != null ? `/${r.ball + 1}` : ''}</span><span>{when(r.at)}</span>
              {r.serverSeed ? <button type="button" className={styles.link} onClick={() => onVerify({ game: r.game, server: r.serverSeed, client: r.client, nonce: r.nonce })}>Verify</button> : <span className={styles.dim}>hidden</span>}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

function Verify({ init }) {
  const [game, setGame] = useState(init?.game || 'roulette')
  const [server, setServer] = useState(init?.server || ''), [client, setClient] = useState(init?.client || ''), [nonce, setNonce] = useState(init?.nonce ?? 0)
  const [o, setO] = useState({}), [out, setOut] = useState(null), [hash, setHash] = useState('')
  const run = async () => {
    if (!/^[0-9a-f]{64}$/i.test(server.trim())) { setOut({ err: 'Server seed must be 64 hex characters.' }); return }
    setHash(await sha256hex(server.trim()))
    setOut({ rows: await derive(game, server.trim(), client.trim() || 'default', Math.max(0, Math.floor(Number(nonce)) || 0), o) })
  }
  return (
    <div className={styles.pane}>
      <label className={styles.fld}><span className={styles.lab}>Game</span>
        <select className={styles.in} value={game} onChange={(e) => { setGame(e.target.value); setOut(null) }}>{Object.entries(GAME_NAMES).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label>
      <label className={styles.fld}><span className={styles.lab}>Server seed</span><input className={styles.in} value={server} onChange={(e) => setServer(e.target.value)} placeholder="64 hex chars" /></label>
      <label className={styles.fld}><span className={styles.lab}>Client seed</span><input className={styles.in} value={client} onChange={(e) => setClient(e.target.value)} placeholder="default" /></label>
      <label className={styles.fld}><span className={styles.lab}>Nonce</span><input className={styles.in} type="number" min="0" value={nonce} onChange={(e) => setNonce(e.target.value)} /></label>
      {(GAME_OPTS[game] || []).map((f) => (
        <label key={f.k} className={styles.fld}><span className={styles.lab}>{f.label}</span><input className={styles.in} type="number" min={f.min} max={f.max} value={o[f.k] ?? f.def} onChange={(e) => setO({ ...o, [f.k]: e.target.value })} /></label>
      ))}
      <button type="button" className={styles.cta} onClick={run}>Verify</button>
      {out?.err && <p className={styles.bad}>{out.err}</p>}
      {out?.rows && (
        <div className={styles.res}>
          <div><span className={styles.lab}>SHA-256 of server seed (must equal the hash shown before your bet)</span><code>{hash}</code></div>
          {out.rows.map((r, i) => <div key={i}><span className={styles.lab}>{r.label}</span><code>{r.value}</code></div>)}
        </div>
      )}
    </div>
  )
}

function Live({ onVerify }) {
  const [rows, setRows] = useState(null)
  useEffect(() => {
    const get = (p) => fetch(`${WORKER}${p}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }).then((r) => r.json()).catch(() => ({}))
    Promise.all([get('/crash/state'), get('/jackpot/state')]).then(([c, j]) => setRows([
      ...(c.fair || []).map((r) => ({ ...r, game: 'crash', res: r.crashAt != null ? `${r.crashAt.toFixed(2)}x` : null })),
      ...(j.fair || []).map((r) => ({ ...r, game: 'jackpot', res: r.ticket != null ? r.ticket.toFixed(6) : null })),
    ]))
  }, [])
  return (
    <div className={styles.pane}>
      <p>Crash and Jackpot rounds are shared by everyone, so each round has its own server seed. Its hash is shown before the round starts, and the seed is revealed when it ends. The client seed is <code>crash-ROUND</code> or <code>jackpot-ROUND</code> and the nonce is 0.</p>
      {!rows ? <p>Loading...</p> : !rows.length ? <p className={styles.note}>No rounds yet.</p> : (
        <div className={styles.tbl}>
          {rows.map((r) => (
            <div key={`${r.game}${r.seq}`} className={styles.tr}>
              <span>{GAME_NAMES[r.game]} #{r.seq}</span><span className={styles.dim} title={r.hash || ''}>{short(r.hash)}</span><span>{r.res || 'live'}</span>
              {r.seed ? <button type="button" className={styles.link} onClick={() => onVerify({ game: r.game, server: r.seed, client: `${r.game}-${r.seq}`, nonce: 0 })}>Verify</button> : <span className={styles.dim}>hidden</span>}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

function Logs() {
  const [rows, setRows] = useState(null), [user, setUser] = useState(''), [game, setGame] = useState('')
  const load = useCallback(async () => {
    const r = await workerPost('/fair/log', { limit: 200, user: user.trim() || undefined, game: game || undefined })
    setRows(r.ok ? r.data.rounds || [] : [])
  }, [user, game])
  useEffect(() => { load() }, [load])
  const csv = () => {
    const head = 'time,user,game,bet,payout,nonce,ball,client_seed,server_hash,server_seed'
    const body = (rows || []).map((r) => [r.at, r.user, r.game, r.bet, r.payout, r.nonce, r.ball ?? '', r.client, r.hash, r.serverSeed || ''].join(','))
    const url = URL.createObjectURL(new Blob([[head, ...body].join('\n')], { type: 'text/csv' }))
    const a = document.createElement('a'); a.href = url; a.download = 'fair-log.csv'; a.click(); URL.revokeObjectURL(url)
  }
  return (
    <div className={styles.pane}>
      <div className={styles.logBar}>
        <input className={styles.in} value={user} onChange={(e) => setUser(e.target.value)} placeholder="Player" />
        <select className={styles.in} value={game} onChange={(e) => setGame(e.target.value)}><option value="">All games</option>{Object.entries(GAME_NAMES).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select>
        <button type="button" className={styles.copy} onClick={csv}>CSV</button>
      </div>
      {!rows ? <p>Loading...</p> : !rows.length ? <p className={styles.note}>No rounds.</p> : (
        <div className={styles.tbl}>
          {rows.map((r) => (
            <div key={r.id} className={`${styles.tr} ${styles.trLog}`}>
              <span>{when(r.at)}</span><b>{r.user}</b><span>{GAME_NAMES[r.game] || r.game}</span>
              <span>{r.bet} / {r.payout}</span><span>n{r.nonce ?? '-'}</span><span className={styles.dim} title={r.hash || ''}>{short(r.hash)}</span>
              <span className={r.serverSeed ? '' : styles.dim}>{r.serverSeed ? 'revealed' : 'hidden'}</span>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}

export default function ProvablyFair({ onClose }) {
  const [tab, setTab] = useState('overview'), [init, setInit] = useState(null), [admin, setAdmin] = useState(false)
  useEffect(() => { workerPost('/fair/log', { limit: 1 }).then((r) => setAdmin(r.ok)) }, [])
  useEffect(() => { const k = (e) => e.key === 'Escape' && onClose(); window.addEventListener('keydown', k); return () => window.removeEventListener('keydown', k) }, [onClose])
  const tabs = [['overview', 'Overview'], ['seeds', 'Seeds'], ['live', 'Live rounds'], ['verify', 'Verify'], ...(admin ? [['logs', 'Logs']] : [])]
  return (
    <div className={styles.ov} onMouseDown={(e) => e.target === e.currentTarget && onClose()}>
      <div className={styles.modal} role="dialog" aria-label="Provably Fair">
        <div className={styles.top}><h3>Provably Fair</h3><button type="button" className={styles.x} onClick={onClose} aria-label="Close"><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18" /></svg></button></div>
        <div className={styles.tabs}>{tabs.map(([k, l]) => <button key={k} type="button" className={tab === k ? styles.on : ''} onClick={() => setTab(k)}>{l}</button>)}</div>
        {tab === 'overview' && <Overview />}
        {tab === 'seeds' && <Seeds onVerify={(v) => { setInit(v); setTab('verify') }} />}
        {tab === 'live' && <Live onVerify={(v) => { setInit(v); setTab('verify') }} />}
        {tab === 'verify' && <Verify init={init} key={init ? `${init.server}${init.nonce}` : 'x'} />}
        {tab === 'logs' && <Logs />}
      </div>
    </div>
  )
}
